In [3]:
import pandas as pnd
import heapq
from collections import Counter

iris = pnd.read_csv('data/iris.csv')

In [43]:
import numpy as np

data_train = np.array(iris.iloc[:, 0:4])
data_train = data_train[:20]

print(data_train)
print(data_train[:,0])
# print(np.average(data_train[:20][0]))
# print(np.sum(data_train[:20][1]))
# data_train

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1]


In [61]:
class KMeans:
    
    # k -> jumlah kelas
    # eps -> epsilon atau toleransi error. akan menjadi threshold jika error < eps maka sudah konvergen
    # max_iter -> jumlah iterasi maksimal yang diperbolehkan
    def __init__ (self, k=2, eps=0.1, max_iter=1000):
        self.k = k
        self.eps = eps
        self.max_iter = max_iter
        self.centroids = []
        self.data = None
        
    def fit(self, data):
        self.data = data
        self.initCentroid()
        i = 0
        error = 1
        while error > self.eps and i <= self.max_iter :
            self.initClassClassification()
            self.assignClassClassification()
            prev_centroids = self.centroids
            current_centroids = self.calculateCentroid()
#             print(prev_centroids)
#             print(current_centroids)
            error = self.calculateError(current_centroids)
#             print(error)
#             print(self.centroids)
            if error > self.eps :
                self.centroids = current_centroids
#             self.setCentroid(self.calculateCentroid())
            i += 1
            
        
    def initCentroid(self):
        for i in range(self.k) :
            self.centroids.append(self.data[i])
    
    def initClassClassification(self) :
        self.classifications = {}
        for i in range (self.k):
            self.classifications[i] = []
            
    def assignClassClassification(self) :
        for i in range (len(self.data)) :
            distances = [self.calculateDistance(self.data[i], centroid) for centroid in self.centroids]
            classification = distances.index(min(distances))
            self.classifications[classification].append(i)
            
    def calculateDistance(self, vec1, vec2) :
#         for v1, v2 in zip(vec1, vec2):
#             print(np.linalg.norm(v1-v2) )
        return np.sum([np.linalg.norm(v1-v2) for v1, v2 in zip(vec1, vec2)])
    
    def calculateCentroid(self) :
        centroids = []
#         print(self.k)
        for i in range(self.k) :
            centroid = []
#             print(len(self.data[0]))
            for j in range(len(self.data[0]))  :
#                 print(i, j)
#                 print(self.data[self.classifications[i],j])
                centroid.append(np.average(self.data[self.classifications[i],j]))
#             print(np.sum(data_train[self.classifications[1]][3]))
            centroids.append(np.array(centroid))
        return centroids
    
    def calculateError(self, centroids) :
        error = 0
        for i in range (len(self.data)) :
            distance = self.calculateDistance(self.data[i], centroids[self.getClusterIndex(i)])
            error += distance
        return error
    
    def getClusterIndex(self, idx) :
        for k in range(self.k) :
            if idx in self.classifications[k] :
                return k
        

clf = KMeans(k=4)
clf.fit(data_train)


10.07878787878788
[array([5.1, 3.5, 1.4, 0.2]), array([4.9, 3. , 1.4, 0.2]), array([4.7, 3.2, 1.3, 0.2]), array([4.6, 3.1, 1.5, 0.2])]
8.508333333333335
[array([5.33636364, 3.77272727, 1.46363636, 0.28181818]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.75, 3.3 , 1.45, 0.2 ]), array([4.475, 3.1  , 1.35 , 0.2  ])]
8.20952380952381
[array([5.45  , 3.875 , 1.475 , 0.3125]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.86666667, 3.41666667, 1.43333333, 0.21666667]), array([4.43333333, 3.        , 1.33333333, 0.16666667])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.9       , 3.42857143, 1.42857143, 0.22857143]), array([4.43333333, 3.        , 1.33333333, 0.16666667])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.2333333

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666

8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.86666667, 3.03333333, 1.43333333, 0.13333333]), array([4.93333333, 3.46666667, 1.45      , 0.23333333]), array([4.5  , 3.05 , 1.325, 0.175])]
8.126190476190475
[array([5.5       , 3.92857143, 1.48571429, 0.31428571]), array([4.8666666